export const SLOTS_FETCHED = 'SLOTS_FETCHED';
export const STAFF_FETCHED = 'STAFF_FETCHED';
export const DATE_SELECTED = 'DATE_SELECTED';
export const TIME_SLOT_SELECTED = 'TIME_SLOT_SELECTED';
export default SLOTS_FETCHED;
