export const MONTH_SELECTED = 'MONTH_SELECTED';
export const SLOTS_FETCHED = 'SLOTS_FETCHED';
export const STAFF_SELECTED = 'STAFF_SELECTED';
export const STAFF_FETCHED = 'STAFF_FETCHED';
export const DATE_SELECTED = 'DATE_SELECTED';
export default STAFF_SELECTED;
